### ISSUE TITLE
What Tiles are possible for the connection?

### ISSUE THREAD

**Issue by rooootdor** [bachya/pytile#111]
Hey! I would like to know which of the tiles (https://www.tile.com/) are possible to use with this python API? are all tiles possible for usage?

**Comment by bachya** [comment]
The API is reverse-engineered, so it isn't possible to know for sure, but I would expect that any Tile can be "seen" by this library.

**Comment by rooootdor** [comment]
which tile was this API tested on if that's ok to ask?

**Comment by bachya** [comment]
I originally used the Mate and Slim.

**Comment by rooootdor** [comment]
thanks!!

**Comment by rooootdor** [comment]
Will this API work on older tiles? 2020 edition?

**Comment by bachya** [comment]
As I mentioned, the API is reverse-engineered, so it isn't possible to know for sure, but I would expect so.

Closing this as answered. Let me know if any issues arise.
