### ISSUE TITLE
Does this software preclude the need to use the Tile app?

### ISSUE THREAD

**Issue by CalamariAce** [bachya/pytile#339]
Does this software only work when someone is running the Tile bluetooth app in proximity to the Tile device? Or can it still get some information from the Tile device by itself (like detecting its presence) without an active connection to the Tile bluetooth app?

**Comment by bachya** [comment]
This library speaks to the Tile cloud API, so in a sense, it requires the Tile app (since that's what Tiles communicate with).

**Comment by CalamariAce** [comment]
Ahh ok, got it. Thanks!
