### ISSUE TITLE
Unauthorized Request Error

### ISSUE THREAD

**Issue by kumaruday691** [bachya/pytile#48]
I recently bought a tile mate, associated it with an account, and ran the sample script shown in the README file.

I get the following error:

```
pytile.errors.RequestError: Error requesting data from users/xxxx-xxxx-x-xxx-x-xxx/user_tiles: 401, message='Unauthorized', url=URL('https://production.tile-api.com/api/v1/users/xxxx-xxxx-x-xxx-x-xxx/user_tiles')
```

I checked the entered credentials to login on the app again, and I had no problem logging in.

Please let me know if i am missing something here or is this a known issue?

Thanks

**Comment by bachya** [comment]
@kumaruday691 You are using [this script](https://github.com/bachya/pytile/blob/dev/examples/test_api.py) to test?

I just used that script with my credentials and everything worked fine. So, I'm guessing one of two things:

1. You entered your credentials into the script incorrectly.
2. There's something about your account/Tiles that are different.

Please triple-check #1. If that isn't the issue, you will need to determine what's different about your account (perhaps by using something like [Charles Proxy](https://www.charlesproxy.com/) to sniff the traffic between the Tile mobile app and the Tile cloud API).

**Comment by kumaruday691** [comment]
the sample script i was using is not the same as the script you mentioned in the comment. The one i was using, was not using client session in the async_login method. 

But the one you mentioned works just fine now. 

Thank you
