### ISSUE TITLE
add the ability to measure the distance, how far the tile is away from the phone or laptop

### ISSUE THREAD

**Issue by Mathayo** [bachya/pytile#60]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Comment by bachya** [comment]
Is this available in the API that this library uses?

**Comment by Mathayo** [comment]
I don't believe so, thought this is something that can be built into the api

**Comment by bachya** [comment]
This isn't something that the Tile API provides, so going to close.
