### ISSUE TITLE
Update home-assistant Tile intergration to 5.0.1

### ISSUE THREAD

**Issue by rolfberkenbosch** [bachya/pytile#62]
Hi there, I saw that the intergration plugin for home-assistant is still using 4.0.0 pypi lib. What i really want to see if it is possible is the lost_timestamp field. So that i now when the tile had has a location update.

**Comment by bachya** [comment]
Hi @rolfberkenbosch – yes, this is possible. Once these Home Assistant PRs are merged:

* https://github.com/home-assistant/core/pull/43064
* https://github.com/home-assistant/core/pull/43065
* https://github.com/home-assistant/core/pull/43071

...I will submit a new PR with your request.

**Comment by bachya** [comment]
The last Home Assistant PR was merged recently, so I'll get moving on this.

**Comment by bachya** [comment]
This functionality will be included via https://github.com/home-assistant/core/pull/45681, so closing this as complete.
