### ISSUE TITLE
Filter by tile_type?

### ISSUE THREAD

**Issue by keithfraley** [bachya/pytile#7]
Is there currently a way to only bring back reports from the TILE itself? Right now I only see a way to bring back all data, including phone records.  Obviously one can filter after the request is delivered, but would save on bandwidth if that was done at run time.

**Comment by bachya** [comment]
Unfortunately, there is no obvious way to do this via the reverse-engineered private API. I imagine that unless you have hundreds of Tiles, requesting all data and parsing shouldn't hurt too badly.
