### ISSUE TITLE
SSL Certificate Error

### ISSUE THREAD

**Issue by leob19** [bachya/pytile#71]
**Describe the bug**
Getting the following error when trying to authenticate:

aiohttp.client_exceptions.ClientConnectorCertificateError: Cannot connect to host production.tile-api.com:443 ssl:True [SSLCertVerificationError: (1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self signed certificate in certificate chain (_ssl.c:1123)')]

**To Reproduce**
```
async def main() -> None:
    """Run!"""
    async with ClientSession() as session:
        api = await async_login("myEmail", "myPwd", session)
asyncio.run(main())

```
**Expected behavior**
Successful connection.

**Screenshots**

**Additional context**
Running Python 3.9 on Mac from virtual environment.

thx for helping a noob

**Comment by bachya** [comment]
This technical isn't a bug with this library, but with certificate verification on the unpublished Tile API (and one that doesn't seem to occur with every user). This can be addressed by instructing `aiohttp` to use a `ClientSession` that doesn't do TLS verification:

```python
from aiohttp import ClientSession, TCPConnector
from pytile import async_login


async def main() -> None:
    """Run!"""
    async with ClientSession(connector=TCPConnector(verify_ssl=False)) as session:
        api = await async_login("myEmail", "myPwd", session)

asyncio.run(main())
```
