### ISSUE TITLE
Full location history

### ISSUE THREAD

**Issue by tonetto** [bachya/pytile#73]
**Is your feature request related to a problem? Please describe.**
`pytile` currently fetches the last-known location of a tile, but Premium services provide up to 30 days of location history. While the app unfortunately does not seem to have an export function this could be a nice addition to your library.

**Describe the solution you'd like**
Function to retrieve all location history of a tile, not just the last known, along with corresponding timestamps.

**Additional context**
![tile_loc_history](https://user-images.githubusercontent.com/1403006/120348715-b7bc0880-c2fd-11eb-9acc-4e40afb15a20.jpeg)

**Comment by bachya** [comment]
I unfortunately don't have Tile's premium services, so I would need someone to submit a PR with this functionality.

**Comment by tonetto** [comment]
I'd be happy to look into it. Do you have any idea where I could start, like an endpoint for their API which could reply with the history?

**Comment by bachya** [comment]
The common way to explore something like this is with a proxy explorer app like [Charles](https://www.charlesproxy.com): as you're using the app, it will record the HTTP requests.
