### ISSUE TITLE
Error messagee in console

### ISSUE THREAD

**Issue by MikeFlach** [bachya/pytile#89]
Hello,

When I run the example script I do seen to get the updated tile locations, but the following is dumped to the console screen for each tile queried...

"Missing last_tile_state; can't report location info"

Is this normal or is something not working correctly on my end?

Thank you for all the handwork on this fantastic library!

Best,
Michael

**Comment by bachya** [comment]
Hi Michael,

This is "expected" in that, if that data is missing, you'll get that error message:

https://github.com/bachya/pytile/blob/e8b24d18ab54f8f1eb459c69ba47d903ad0b0cf0/pytile/tile.py#L131-L137

Before we assume something is wrong with your setup, let's see if you're getting that data elsewhere. In the example script, set the log level to `logging.DEBUG`:

https://github.com/bachya/pytile/blob/e8b24d18ab54f8f1eb459c69ba47d903ad0b0cf0/examples/test_api.py#L18

...then run it again. This will dump a _ton_ of JSON to your console. Take a look and see if you see location data (latitude/longitude, some sort of timestamp, etc.) elsewhere in that structure.
