### ISSUE TITLE
Session has expired; make a new one!

### ISSUE THREAD

**Issue by jopoku** [bachya/pytile#9]
**We keep getting session failed when we run the example.py file. Any assistance would be greatly appreciated.

Issue may be due to the use of TCPConnector definition but not sure.
Below is my example.py

```
[root@lab pytile]# cat example.py
"""Run an example script to quickly test."""
import asyncio
import ssl
import aiohttp

from aiohttp import ClientSession
from pytile import Client
from pytile.errors import TileError

async def main():
"""Run."""
sslcontext = ssl.create_default_context()
conn = aiohttp.TCPConnector(ssl=sslcontext)
async with ClientSession(connector=conn) as websession:
try:

""" Create a client: """"
client = Client("joseph.opoku@gmail.com", "removed#2", websession)

await client.async_init()
print("Showing active Tiles:")
print(await client.tiles.all())
print("Showing all Tiles:")
print(await client.tiles.all(show_inactive=True))
except TileError as err:
print(err)
asyncio.get_event_loop().run_until_complete(main())
```

**To Reproduce**
1. Copy the example.py above and run with valid logins
2. See error

**Expected behavior**
[root@lab pytile]# python example.py

Showing active Tiles:

Session has expired; make a new one!

[root@lab pytile]#

**Additional context**
My python version is 3.7.1
[jopoku@lab ~]$ python -V
Python 3.7.1
[jopoku@lab ~]$

**Comment by bachya** [comment]
Why are you using a TCPConnector? Why not just use a ClientSession [as is shown in the example](https://github.com/bachya/pytile/blob/7e3adbeff328e25a796b347486792ea57dd8c3e1/example.py#L12)?

**Comment by jopoku** [comment]
Wow, I feel like a kid in a candy store. It finally worked for me. It was not working earlier.

**Comment by jopoku** [comment]
Sorry I mean [as shown in the example](https://github.com/bachya/pytile/blob/7e3adbeff328e25a796b347486792ea57dd8c3e1/example.py#L12) finally worked

**Comment by bachya** [comment]
Great! I'll close this out; feel free to open new issues if you have them.
