### ISSUE TITLE
strange/inconsistent version numbering since 2022.1.0

### ISSUE THREAD

**Issue by onkelbeh** [bachya/pytile#94]
Hello Aaron,

**Is your feature request related to a problem? Please describe.**

Since 2022.1.0 you ~~(and some other guys)~~ are using a bad new style for version numbers padded with zeros, e.g at Github, you are using the 2nd digit padded with a zero, perhaps this should look better in sorted lists, as you want to treat this as a month in a version number looking like a date.

This is causing some trouble, because a lot of package managers (like portage at Gentoo, or Pypi) are treating the version number segments as integers, this is a hard rule in semver-2.0.

We are using a set of automated build scripts, which now is in trouble. Ok, currently, I patched it, it now rewrites the _wrong_ formatted version number, but I would like to adress the problem at it's source (->you) :-)

According to [semver-2.0](https://semver.org/#spec-item-2):

"A normal version number MUST take the form X.Y.Z where X, Y, and Z are non-negative integers, and **MUST NOT contain leading zeroes**. X is the major version, Y is the minor version, and Z is the patch version. Each element MUST increase numerically. For instance: 1.9.0 -> 1.10.0 -> 1.11.0."

**Describe the solution you'd like**
Please avoid using leading zeroes in version numbers.

**Additional context**

**Comment by bachya** [comment]
Let's centralize the discussion: https://github.com/bachya/simplisafe-python/issues/309
